[project]
name = "telavox-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

[tool.uv.workspace]
members = ["src/apps/onboarding-mcp", "src/libs/lib_logger"]

[dependency-groups]
dev = ["pre-commit>=4.5.1", "ruff>=0.15.0"]
